### ISSUE TITLE
Maybe warn people that the created_at, modified_at columns are set with python, not with triggers

### ISSUE THREAD

**Issue by mw44118** [drneox/django-paranoid#17]
Hi -- big fan of paranoid model.  

One tiny thing: If you use some kind of bulk-upload feature that skips around the models, then these columns will not be set.

Maybe just add a paragraph to the README warning about this.

Thanks for making such a coo project and sharing it with us!

**Comment by drneox** [comment]
hello @mw44118, thanks for the feedback, maybe i work in this solve it soon.
