### ISSUE TITLE
Soft deletes and unique columns don't always play nice

### ISSUE THREAD

**Issue by mw44118** [drneox/django-paranoid#18]
I have a table named xyz with a unique column "email_address".

Since paranoidmodel just does soft deletes, once I create an email address, even though I delete it, I can't insert a row with the same email address.

I understand what's happening, but this feels wrong...

My home made solution is to make a special partial index:
```
create unique index on xyz (email_address) where deleted_at is null
```
And this works fine, but it would be super cool if this happened automatically.

**Comment by mw44118** [comment]
Here's how I use a django constraint to create the partial unique index:

```
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["email_address"],
                name="unique_email_address",
                condition=models.Q(deleted_at=None))
         ]
```

**Comment by woojunro** [comment]
You can use `obj.delete(True)` to hard-delete a model object, or you can just restore the soft-deleted object instead of creating a new one.

**Comment by smac89** [comment]
@mw44118 I think you should change the condition to `models.Q(deleted_at__isnull=True)`
